default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: danci
      password: Konyenki3
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: flights_development

test:
  <<: *default
  database: flights_test

production:
  <<: *default
  database: flights_production